[General]
	#The number of item stacks held in a basic unit of storage.
	#1x1 drawers hold 8 units, 1x2 drawers hold 4 units, 2x2 drawers hold 2 units.
	#Half-depth drawers hold half those amounts.
	baseStackStorage = 4
	#Controller range defines how far away a drawer can be connected
	#on X, Y, or Z planes.  The default value of 50 gives the controller a very
	#large range, but not beyond the chunk load distance.
	#Range: 1 ~ 75
	controllerRange = 50
	#Whether redstone upgrades should emit an analog redstone signal, requiring
	#the use of a comparator to read it.
	enableAnalogRedstone = true
	enableUI = true
	enableSidedInput = true
	enableSidedOutput = true
	enableItemConversion = true
	enableExtraCompactingRules = true
	debugTrace = false
	#Allows drawers to be pulled from their block and inserted into another block.
	enableDetachedDrawers = true
	#Drawers track the capacity upgrades from the block they were taken from.
	#Drawers can only be placed back into a block with the same or lower max capacity.
	#Drawers can still only be inserted into a block with enough capacity for the items held.
	forceDetachedDrawersMaxCapacityCheck = false
	#If enabled, carrying filled drawers in your inventory gives slowness debuff,
	#unless a Portability Upgrade is used.
	heavyDrawers = false
	#If enabled, players can lock drawer interactions to just themselves.
	enablePersonalKey = true

[StorageUpgrades]
	level1Mult = 2
	level2Mult = 4
	level3Mult = 8
	level4Mult = 16
	level5Mult = 32
	#Balance upgrades allow same-item slots to balance out their amounts when items are
	#added or removed from a lot.  Works across networks when acting through a controller.
	enableBalanceUpgrade = true

[Integration]
	#When true, shows quantity as NxS + R (by stack size) rather than count
	wailaStackRemainder = true
	#When true, does not show current quantities unless quantify key was used
	wailaRespectQuantifyKey = false
