ItemEvents.modifyTooltips(event => {
  event.add(
    [
      'farmersdelight:apple_pie', 
      'farmersdelight:sweet_berry_cheesecake', 
      'farmersdelight:chocolate_pie', 
      'farmersdelight:sweet_berry_cookie', 
      'farmersdelight:honey_cookie', 
      'farmersdelight:melon_popsicle', 
      'farmersdelight:glow_berry_custard'
    ],
    [
      Text.translate('collectionTooltips.cooking_collection'), 
      Text.translate('collectionTooltips.sweets_farmers_delight_completion')
    ])
  event.add(
    [
      'farmersdelight:fruit_salad', 
      'farmersdelight:mixed_salad', 
      'farmersdelight:nether_salad'
    ],
    [
      Text.translate('collectionTooltips.cooking_collection'), 
      Text.translate('collectionTooltips.salads_farmers_delight_completion')
    ])
  event.add(
    [
      'farmersdelight:egg_sandwich', 
      'farmersdelight:chicken_sandwich', 
      'farmersdelight:hamburger', 
      'farmersdelight:bacon_sandwich'
    ],
    [
      Text.translate('collectionTooltips.cooking_collection'), 
      Text.translate('collectionTooltips.sandwiches_farmers_delight_completion')
    ])
  event.add(
    [
      'farmersdelight:beef_stew', 
      'farmersdelight:bone_broth', 
      'farmersdelight:chicken_soup', 
      'farmersdelight:vegetable_soup', 
      'farmersdelight:fish_stew', 
      'farmersdelight:pumpkin_soup', 
      'farmersdelight:baked_cod_stew'
    ],
    [
      Text.translate('collectionTooltips.cooking_collection'), 
      Text.translate('collectionTooltips.soups_farmers_delight_completion')
    ])
  event.add(
    [
      'farmersdelight:dumplings', 
      'farmersdelight:fried_rice', 
      'farmersdelight:cabbage_rolls'
    ],
    [
      Text.translate('collectionTooltips.cooking_collection'), 
      Text.translate('collectionTooltips.asian_foods_farmers_delight_completion')
    ])
  event.add(
    [
      'farmersdelight:steak_and_potatoes', 
      'farmersdelight:mutton_wrap', 
      'farmersdelight:bacon_and_eggs', 
      'farmersdelight:stuffed_potato', 
      'farmersdelight:mushroom_rice', 
      'farmersdelight:ratatouille'
    ],
    [
      Text.translate('collectionTooltips.cooking_collection'), 
      Text.translate('collectionTooltips.dinners_farmers_delight_completion')
    ])
  event.add(
    [
      'farmersdelight:pasta_with_meatballs', 
      'farmersdelight:pasta_with_mutton_chop', 
      'farmersdelight:vegetable_noodles', 
      'farmersdelight:squid_ink_pasta', 
      'farmersdelight:noodle_soup'
    ],
    [
      Text.translate('collectionTooltips.cooking_collection'), 
      Text.translate('collectionTooltips.noodles_farmers_delight_completion')
    ])
  event.add(
    [
      'farmersdelight:barbecue_stick', 
      'farmersdelight:grilled_salmon', 
      'farmersdelight:roasted_mutton_chops'
    ],
    [
      Text.translate('collectionTooltips.cooking_collection'), 
      Text.translate('collectionTooltips.bbq_farmers_delight_completion')
    ])
  event.add(
    [
      'farmersdelight:roast_chicken_block', 
      'farmersdelight:stuffed_pumpkin_block', 
      'farmersdelight:honey_glazed_ham_block', 
      'farmersdelight:shepherds_pie_block', 
      'farmersdelight:rice_roll_medley_block'
    ],
    [
      Text.translate('collectionTooltips.cooking_collection'), 
      Text.translate('collectionTooltips.large_meals_farmers_delight_completion')
    ])
  event.add(
    [
      'minecraft:cod', 
      'minecraft:salmon', 
      'minecraft:tropical_fish', 
      'minecraft:pufferfish'
    ],
    [
      Text.translate('collectionTooltips.aquarium'), 
      Text.translate('collectionTooltips.vanilla_completion')
    ])
  event.add(
    [
      'aquaculture:smallmouth_bass', 
      'aquaculture:bluegill', 
      'aquaculture:brown_trout', 
      'aquaculture:carp', 
      'aquaculture:catfish', 
      'aquaculture:gar', 
      'aquaculture:minnow', 
      'aquaculture:muskellunge', 
      'aquaculture:perch'
    ],
    [
      Text.translate('collectionTooltips.aquarium'), 
      Text.translate('collectionTooltips.freshwater_completion')
    ])
  event.add(
    [
      'aquaculture:bayad', 
      'aquaculture:boulti', 
      'aquaculture:capitaine', 
      'aquaculture:synodontis'
    ],
    [
      Text.translate('collectionTooltips.aquarium'), 
      Text.translate('collectionTooltips.arid_completion')
    ])
  event.add(
    [
      'aquaculture:atlantic_cod', 
      'aquaculture:blackfish', 
      'aquaculture:pacific_halibut', 
      'aquaculture:atlantic_halibut', 
      'aquaculture:atlantic_herring', 
      'aquaculture:pink_salmon', 
      'aquaculture:pollock', 
      'aquaculture:rainbow_trout'
    ],
    [
      Text.translate('collectionTooltips.aquarium'), 
      Text.translate('collectionTooltips.artic_completion')
    ])
  event.add(
    [
      'aquaculture:jellyfish', 
      'aquaculture:red_grouper', 
      'aquaculture:tuna'
    ],
    [
      Text.translate('collectionTooltips.aquarium'), 
      Text.translate('collectionTooltips.saltwater_completion')
    ])
  event.add(
    [
      'aquaculture:box_turtle', 
      'aquaculture:leech', 
      'aquaculture:goldfish'
    ],
    [
      Text.translate('collectionTooltips.aquarium'), 
      Text.translate('collectionTooltips.swamp_completion')
    ])
  event.add(
    [
      'aquaculture:brown_shrooma', 
      'aquaculture:red_shrooma'
    ],
    [
      Text.translate('collectionTooltips.aquarium'), 
      Text.translate('collectionTooltips.mushroom_completion')
    ])
  event.add(
    [
      'aquaculture:arapaima', 
      'aquaculture:piranha', 
      'aquaculture:tambaqui', 
      'aquaculture:arrau_turtle'
    ],
    [
      Text.translate('collectionTooltips.aquarium'), 
      Text.translate('collectionTooltips.jungle_completion')
    ])
  event.add(
    [
      'aquaculture:starshell_turtle'
    ],
    [
      Text.translate('collectionTooltips.aquarium'), 
      Text.translate('collectionTooltips.twilight')
    ])
  event.add(
    [
      'minecraft:apple', 
      'minecraft:bamboo', 
      'minecraft:beetroot_seeds', 
      'minecraft:brown_mushroom', 
      'minecraft:cactus', 
      'minecraft:carrot', 
      'minecraft:cocoa_beans', 
      'minecraft:glow_berries', 
      'minecraft:kelp', 
      'minecraft:melon_slice', 
      'minecraft:potato', 
      'minecraft:pumpkin_seeds', 
      'minecraft:pumpkin', 
      'minecraft:red_mushroom', 
      'minecraft:sugar_cane', 
      'minecraft:sweet_berries', 
      'minecraft:wheat_seeds'
    ],
    [
      Text.translate('collectionTooltips.flora_compendium'), 
      Text.translate('collectionTooltips.vanilla_foods_completion')
    ])
  event.add(
    [
      'farmersdelight:cabbage_seeds', 
      'farmersdelight:onion', 
      'farmersdelight:rice', 
      'farmersdelight:tomato_seeds'
    ],
    [
      Text.translate('collectionTooltips.flora_compendium'), 
      Text.translate('collectionTooltips.moded_foods_completion')
    ])
  event.add(
    [
      'minecraft:allium', 
      'minecraft:azure_bluet', 
      'minecraft:blue_orchid', 
      'minecraft:cornflower', 
      'minecraft:dandelion', 
      'minecraft:lilac', 
      'minecraft:lily_of_the_valley', 
      'minecraft:orange_tulip', 
      'minecraft:oxeye_daisy', 
      'minecraft:peony', 
      'minecraft:pink_tulip', 
      'minecraft:poppy', 
      'minecraft:red_tulip', 
      'minecraft:rose_bush', 
      'minecraft:sunflower', 
      'minecraft:white_tulip', 
      'minecraft:wither_rose', 
      'minecraft:torchflower_seeds'
    ],
    [
      Text.translate('collectionTooltips.flora_compendium'), 
      Text.translate('collectionTooltips.vanilla_flower_completion')
    ])
  event.add(
    [
      'minecraft:acacia_sapling', 
      'minecraft:azalea', 
      'minecraft:birch_sapling', 
      'minecraft:cherry_sapling', 
      'minecraft:dark_oak_sapling', 
      'minecraft:jungle_sapling', 
      'minecraft:oak_sapling', 
      'minecraft:spruce_sapling', 
      'minecraft:mangrove_propagule'
    ],
    [
      Text.translate('collectionTooltips.flora_compendium'), 
      Text.translate('collectionTooltips.vanilla_sapling_completion')
    ])
  event.add(
    [
      'minecraft:flowering_azalea', 
      'minecraft:moss_block', 
      'minecraft:moss_carpet', 
      'minecraft:pink_petals', 
      'minecraft:spore_blossom', 
      'minecraft:big_dripleaf', 
      'minecraft:sea_pickle', 
      'minecraft:lily_pad'
    ],
    [
      Text.translate('collectionTooltips.flora_compendium'), 
      Text.translate('collectionTooltips.misc_flora_completion')
    ])
  event.add(
    [
      'minecraft:cobblestone', 
      'minecraft:mossy_cobblestone', 
      'minecraft:cobbled_deepslate', 
      'minecraft:diorite', 
      'minecraft:granite', 
      'minecraft:andesite', 
      'minecraft:sandstone', 
      'minecraft:red_sandstone', 
      'minecraft:calcite', 
      'minecraft:dripstone_block', 
      'minecraft:pointed_dripstone', 
      'minecraft:smooth_basalt', 
      'minecraft:tuff', 
      'minecraft:obsidian'
    ],
    [
      Text.translate('collectionTooltips.mineral_museum'), 
      Text.translate('collectionTooltips.vanilla_blocks_completion')
    ])
  event.add(
    [
      'minecraft:coal', 
      'minecraft:raw_copper', 
      'minecraft:raw_iron', 
      'minecraft:amethyst_shard', 
      'minecraft:raw_gold', 
      'minecraft:redstone', 
      'minecraft:lapis_lazuli', 
      'minecraft:diamond'
    ],
    [
      Text.translate('collectionTooltips.mineral_museum'), 
      Text.translate('collectionTooltips.ore_completion')
    ])

})