ItemEvents.modifyTooltips(event => {
  event.add(
    [
      'farmersdelight:apple_pie', 
      'farmersdelight:sweet_berry_cheesecake', 
      'farmersdelight:chocolate_pie', 
      'farmersdelight:sweet_berry_cookie', 
      'farmersdelight:honey_cookie', 
      'farmersdelight:melon_popsicle', 
      'farmersdelight:glow_berry_custard'
    ],
    [
      Text.translate('collectionTooltips.cooking_collection'), 
      Text.translate('collectionTooltips.sweets_farmers_delight_completion')
    ])
  event.add(
    [
      'farmersdelight:fruit_salad', 
      'farmersdelight:mixed_salad', 
      'farmersdelight:nether_salad'
    ],
    [
      Text.translate('collectionTooltips.cooking_collection'), 
      Text.translate('collectionTooltips.salads_farmers_delight_completion')
    ])
  event.add(
    [
      'farmersdelight:egg_sandwich', 
      'farmersdelight:chicken_sandwich', 
      'farmersdelight:hamburger', 
      'farmersdelight:bacon_sandwich'
    ],
    [
      Text.translate('collectionTooltips.cooking_collection'), 
      Text.translate('collectionTooltips.sandwiches_farmers_delight_completion')
    ])
  event.add(
    [
      'farmersdelight:beef_stew', 
      'farmersdelight:bone_broth', 
      'farmersdelight:chicken_soup', 
      'farmersdelight:vegetable_soup', 
      'farmersdelight:fish_stew', 
      'farmersdelight:pumpkin_soup', 
      'farmersdelight:baked_cod_stew'
    ],
    [
      Text.translate('collectionTooltips.cooking_collection'), 
      Text.translate('collectionTooltips.soups_farmers_delight_completion')
    ])
  event.add(
    [
      'farmersdelight:dumplings', 
      'farmersdelight:fried_rice', 
      'farmersdelight:cabbage_rolls'
    ],
    [
      Text.translate('collectionTooltips.cooking_collection'), 
      Text.translate('collectionTooltips.asian_foods_farmers_delight_completion')
    ])
  event.add(
    [
      'farmersdelight:steak_and_potatoes', 
      'farmersdelight:mutton_wrap', 
      'farmersdelight:bacon_and_eggs', 
      'farmersdelight:stuffed_potato', 
      'farmersdelight:mushroom_rice', 
      'farmersdelight:ratatouille'
    ],
    [
      Text.translate('collectionTooltips.cooking_collection'), 
      Text.translate('collectionTooltips.dinners_farmers_delight_completion')
    ])
  event.add(
    [
      'farmersdelight:pasta_with_meatballs', 
      'farmersdelight:pasta_with_mutton_chop', 
      'farmersdelight:vegetable_noodles', 
      'farmersdelight:squid_ink_pasta', 
      'farmersdelight:noodle_soup'
    ],
    [
      Text.translate('collectionTooltips.cooking_collection'), 
      Text.translate('collectionTooltips.noodles_farmers_delight_completion')
    ])
  event.add(
    [
      'farmersdelight:barbecue_stick', 
      'farmersdelight:grilled_salmon', 
      'farmersdelight:roasted_mutton_chops'
    ],
    [
      Text.translate('collectionTooltips.cooking_collection'), 
      Text.translate('collectionTooltips.bbq_farmers_delight_completion')
    ])
  event.add(
    [
      'farmersdelight:roast_chicken_block', 
      'farmersdelight:stuffed_pumpkin_block', 
      'farmersdelight:honey_glazed_ham_block', 
      'farmersdelight:shepherds_pie_block', 
      'farmersdelight:rice_roll_medley_block'
    ],
    [
      Text.translate('collectionTooltips.cooking_collection'), 
      Text.translate('collectionTooltips.large_meals_farmers_delight_completion')
    ])
  event.add(
    [
      'refurbished_furniture:cheese_toastie', 
      'refurbished_furniture:sweet_berry_jam_toast', 
      'refurbished_furniture:glow_berry_jam_toast', 
      'refurbished_furniture:cooked_vegetable_pizza', 
      'refurbished_furniture:cooked_meatlovers_pizza'
    ],
    [
      Text.translate('collectionTooltips.cooking_collection'), 
      Text.translate('collectionTooltips.mrcrayfish_meals_completion')
    ])
  event.add(
    [
      'minecraft:cod', 
      'minecraft:salmon', 
      'minecraft:tropical_fish', 
      'minecraft:pufferfish'
    ],
    [
      Text.translate('collectionTooltips.aquarium'), 
      Text.translate('collectionTooltips.vanilla_completion')
    ])
  event.add(
    [
      'aquaculture:smallmouth_bass', 
      'aquaculture:bluegill', 
      'aquaculture:brown_trout', 
      'aquaculture:carp', 
      'aquaculture:catfish', 
      'aquaculture:gar', 
      'aquaculture:minnow', 
      'aquaculture:muskellunge', 
      'aquaculture:perch'
    ],
    [
      Text.translate('collectionTooltips.aquarium'), 
      Text.translate('collectionTooltips.freshwater_completion')
    ])
  event.add(
    [
      'aquaculture:bayad', 
      'aquaculture:boulti', 
      'aquaculture:capitaine', 
      'aquaculture:synodontis'
    ],
    [
      Text.translate('collectionTooltips.aquarium'), 
      Text.translate('collectionTooltips.arid_completion')
    ])
  event.add(
    [
      'aquaculture:atlantic_cod', 
      'aquaculture:blackfish', 
      'aquaculture:pacific_halibut', 
      'aquaculture:atlantic_halibut', 
      'aquaculture:atlantic_herring', 
      'aquaculture:pink_salmon', 
      'aquaculture:pollock', 
      'aquaculture:rainbow_trout'
    ],
    [
      Text.translate('collectionTooltips.aquarium'), 
      Text.translate('collectionTooltips.artic_completion')
    ])
  event.add(
    [
      'aquaculture:jellyfish', 
      'aquaculture:red_grouper', 
      'aquaculture:tuna'
    ],
    [
      Text.translate('collectionTooltips.aquarium'), 
      Text.translate('collectionTooltips.saltwater_completion')
    ])
  event.add(
    [
      'aquaculture:box_turtle', 
      'aquaculture:leech', 
      'aquaculture:goldfish'
    ],
    [
      Text.translate('collectionTooltips.aquarium'), 
      Text.translate('collectionTooltips.swamp_completion')
    ])
  event.add(
    [
      'aquaculture:brown_shrooma', 
      'aquaculture:red_shrooma'
    ],
    [
      Text.translate('collectionTooltips.aquarium'), 
      Text.translate('collectionTooltips.mushroom_completion')
    ])
  event.add(
    [
      'aquaculture:arapaima', 
      'aquaculture:piranha', 
      'aquaculture:tambaqui', 
      'aquaculture:arrau_turtle'
    ],
    [
      Text.translate('collectionTooltips.aquarium'), 
      Text.translate('collectionTooltips.jungle_completion')
    ])
  event.add(
    [
      'aquaculture:starshell_turtle'
    ],
    [
      Text.translate('collectionTooltips.aquarium'), 
      Text.translate('collectionTooltips.twilight')
    ])
  event.add(
    [
      'minecraft:apple', 
      'minecraft:bamboo', 
      'minecraft:beetroot_seeds', 
      'minecraft:brown_mushroom', 
      'minecraft:cactus', 
      'minecraft:carrot', 
      'minecraft:cocoa_beans', 
      'minecraft:glow_berries', 
      'minecraft:kelp', 
      'minecraft:melon_slice', 
      'minecraft:potato', 
      'minecraft:pumpkin_seeds', 
      'minecraft:pumpkin', 
      'minecraft:red_mushroom', 
      'minecraft:sugar_cane', 
      'minecraft:sweet_berries', 
      'minecraft:wheat_seeds'
    ],
    [
      Text.translate('collectionTooltips.flora_compendium'), 
      Text.translate('collectionTooltips.vanilla_foods_completion')
    ])
  event.add(
    [
      'farmersdelight:cabbage_seeds', 
      'farmersdelight:onion', 
      'farmersdelight:rice', 
      'farmersdelight:tomato_seeds'
    ],
    [
      Text.translate('collectionTooltips.flora_compendium'), 
      Text.translate('collectionTooltips.moded_foods_completion')
    ])
  event.add(
    [
      'minecraft:allium', 
      'minecraft:azure_bluet', 
      'minecraft:blue_orchid', 
      'minecraft:cornflower', 
      'minecraft:dandelion', 
      'minecraft:lilac', 
      'minecraft:lily_of_the_valley', 
      'minecraft:orange_tulip', 
      'minecraft:oxeye_daisy', 
      'minecraft:peony', 
      'minecraft:pink_tulip', 
      'minecraft:poppy', 
      'minecraft:red_tulip', 
      'minecraft:rose_bush', 
      'minecraft:sunflower', 
      'minecraft:white_tulip', 
      'minecraft:wither_rose', 
      'minecraft:torchflower_seeds'
    ],
    [
      Text.translate('collectionTooltips.flora_compendium'), 
      Text.translate('collectionTooltips.vanilla_flower_completion')
    ])
  event.add(
    [
      'minecraft:acacia_sapling', 
      'minecraft:azalea', 
      'minecraft:birch_sapling', 
      'minecraft:cherry_sapling', 
      'minecraft:dark_oak_sapling', 
      'minecraft:jungle_sapling', 
      'minecraft:oak_sapling', 
      'minecraft:spruce_sapling', 
      'minecraft:mangrove_propagule'
    ],
    [
      Text.translate('collectionTooltips.flora_compendium'), 
      Text.translate('collectionTooltips.vanilla_sapling_completion')
    ])
  event.add(
    [
      'minecraft:flowering_azalea', 
      'minecraft:moss_block', 
      'minecraft:moss_carpet', 
      'minecraft:pink_petals', 
      'minecraft:spore_blossom', 
      'minecraft:big_dripleaf', 
      'minecraft:sea_pickle', 
      'minecraft:lily_pad'
    ],
    [
      Text.translate('collectionTooltips.flora_compendium'), 
      Text.translate('collectionTooltips.vanilla_flora_completion')
    ])
  event.add(
    [
      'regions_unexplored:maple_sapling', 
      'regions_unexplored:orange_maple_sapling', 
      'regions_unexplored:red_maple_sapling'
    ],
    [
      Text.translate('collectionTooltips.flora_compendium'), 
      Text.translate('collectionTooltips.maple_saplings_completion')
    ])
  event.add(
    [
      'regions_unexplored:magnolia_sapling', 
      'regions_unexplored:blue_magnolia_sapling', 
      'regions_unexplored:pink_magnolia_sapling', 
      'regions_unexplored:white_magnolia_sapling'
    ],
    [
      Text.translate('collectionTooltips.flora_compendium'), 
      Text.translate('collectionTooltips.magnolia_saplings_completion')
    ])
  event.add(
    [
      'regions_unexplored:alpha_sapling', 
      'regions_unexplored:apple_oak_sapling', 
      'regions_unexplored:ashen_sapling', 
      'regions_unexplored:bamboo_sapling', 
      'regions_unexplored:baobab_sapling', 
      'regions_unexplored:blackwood_sapling', 
      'regions_unexplored:cypress_sapling', 
      'regions_unexplored:dead_pine_sapling', 
      'regions_unexplored:dead_sapling', 
      'regions_unexplored:enchanted_birch_sapling', 
      'regions_unexplored:eucalyptus_sapling', 
      'regions_unexplored:flowering_sapling', 
      'regions_unexplored:golden_larch_sapling', 
      'regions_unexplored:joshua_sapling', 
      'regions_unexplored:kapok_sapling', 
      'regions_unexplored:larch_sapling', 
      'regions_unexplored:mauve_sapling', 
      'regions_unexplored:palm_sapling', 
      'regions_unexplored:pine_sapling', 
      'regions_unexplored:redwood_sapling', 
      'regions_unexplored:silver_birch_sapling', 
      'regions_unexplored:small_oak_sapling', 
      'regions_unexplored:socotra_sapling', 
      'regions_unexplored:willow_sapling'
    ],
    [
      Text.translate('collectionTooltips.flora_compendium'), 
      Text.translate('collectionTooltips.misc_saplings_completion')
    ])
  event.add(
    [
      'regions_unexplored:maple_shrub', 
      'regions_unexplored:orange_maple_shrub', 
      'regions_unexplored:red_maple_shrub'
    ],
    [
      Text.translate('collectionTooltips.flora_compendium'), 
      Text.translate('collectionTooltips.maple_shrubs_completion')
    ])
  event.add(
    [
      'regions_unexplored:magnolia_shrub', 
      'regions_unexplored:blue_magnolia_shrub', 
      'regions_unexplored:pink_magnolia_shrub', 
      'regions_unexplored:white_magnolia_shrub'
    ],
    [
      Text.translate('collectionTooltips.flora_compendium'), 
      Text.translate('collectionTooltips.magnolia_shrub_completion')
    ])
  event.add(
    [
      'regions_unexplored:acacia_shrub', 
      'regions_unexplored:birch_shrub', 
      'regions_unexplored:cherry_shrub', 
      'regions_unexplored:dark_oak_shrub', 
      'regions_unexplored:jungle_shrub', 
      'regions_unexplored:oak_shrub', 
      'regions_unexplored:spruce_shrub'
    ],
    [
      Text.translate('collectionTooltips.flora_compendium'), 
      Text.translate('collectionTooltips.vanilla_shrubs_completion')
    ])
  event.add(
    [
      'regions_unexplored:ashen_shrub', 
      'regions_unexplored:baobab_shrub', 
      'regions_unexplored:blackwood_shrub', 
      'regions_unexplored:cypress_shrub', 
      'regions_unexplored:dead_pine_shrub', 
      'regions_unexplored:dead_shrub', 
      'regions_unexplored:dead_steppe_shrub', 
      'regions_unexplored:enchanted_birch_shrub', 
      'regions_unexplored:eucalyptus_shrub', 
      'regions_unexplored:flowering_shrub', 
      'regions_unexplored:golden_larch_shrub', 
      'regions_unexplored:joshua_shrub', 
      'regions_unexplored:kapok_shrub', 
      'regions_unexplored:larch_shrub', 
      'regions_unexplored:mangrove_shrub', 
      'regions_unexplored:mauve_shrub', 
      'regions_unexplored:palm_shrub', 
      'regions_unexplored:pine_shrub', 
      'regions_unexplored:redwood_shrub', 
      'regions_unexplored:silver_birch_shrub', 
      'regions_unexplored:small_desert_shrub', 
      'regions_unexplored:socotra_shrub', 
      'regions_unexplored:steppe_shrub', 
      'regions_unexplored:willow_shrub'
    ],
    [
      Text.translate('collectionTooltips.flora_compendium'), 
      Text.translate('collectionTooltips.misc_shrubs_completion')
    ])
  event.add(
    [
      'regions_unexplored:blue_magnolia_flowers', 
      'regions_unexplored:pink_magnolia_flowers', 
      'regions_unexplored:white_magnolia_flowers'
    ],
    [
      Text.translate('collectionTooltips.flora_compendium'), 
      Text.translate('collectionTooltips.magnolia_flowers_completion')
    ])
  event.add(
    [
      'regions_unexplored:black_snowbelle', 
      'regions_unexplored:blue_snowbelle', 
      'regions_unexplored:brown_snowbelle', 
      'regions_unexplored:cyan_snowbelle', 
      'regions_unexplored:gray_snowbelle', 
      'regions_unexplored:green_snowbelle', 
      'regions_unexplored:light_blue_snowbelle', 
      'regions_unexplored:light_gray_snowbelle', 
      'regions_unexplored:lime_snowbelle', 
      'regions_unexplored:magenta_snowbelle', 
      'regions_unexplored:orange_snowbelle', 
      'regions_unexplored:pink_snowbelle', 
      'regions_unexplored:purple_snowbelle', 
      'regions_unexplored:red_snowbelle', 
      'regions_unexplored:white_snowbelle', 
      'regions_unexplored:yellow_snowbelle'
    ],
    [
      Text.translate('collectionTooltips.flora_compendium'), 
      Text.translate('collectionTooltips.snowbelle_completion')
    ])
  event.add(
    [
      'regions_unexplored:alpha_dandelion', 
      'regions_unexplored:alpha_rose', 
      'regions_unexplored:aster', 
      'regions_unexplored:bleeding_heart', 
      'regions_unexplored:blue_lupine', 
      'regions_unexplored:daisy', 
      'regions_unexplored:day_lily', 
      'regions_unexplored:felicia_daisy', 
      'regions_unexplored:fireweed', 
      'regions_unexplored:hibiscus', 
      'regions_unexplored:hyacinth_flowers', 
      'regions_unexplored:hyssop', 
      'regions_unexplored:mallow', 
      'regions_unexplored:orange_coneflower', 
      'regions_unexplored:pink_lupine', 
      'regions_unexplored:poppy_bush', 
      'regions_unexplored:purple_coneflower', 
      'regions_unexplored:purple_lupine', 
      'regions_unexplored:red_lupine', 
      'regions_unexplored:salmon_poppy_bush', 
      'regions_unexplored:tassel', 
      'regions_unexplored:tsubaki', 
      'regions_unexplored:waratah', 
      'regions_unexplored:white_trillium', 
      'regions_unexplored:wilting_trillium', 
      'regions_unexplored:yellow_lupine'
    ],
    [
      Text.translate('collectionTooltips.flora_compendium'), 
      Text.translate('collectionTooltips.misc_flowers_completion')
    ])
  event.add(
    [
      'minecraft:cobblestone', 
      'minecraft:mossy_cobblestone', 
      'minecraft:cobbled_deepslate', 
      'minecraft:diorite', 
      'minecraft:granite', 
      'minecraft:andesite', 
      'minecraft:sandstone', 
      'minecraft:red_sandstone', 
      'minecraft:calcite', 
      'minecraft:dripstone_block', 
      'minecraft:pointed_dripstone', 
      'minecraft:smooth_basalt', 
      'minecraft:tuff', 
      'minecraft:obsidian'
    ],
    [
      Text.translate('collectionTooltips.mineral_museum'), 
      Text.translate('collectionTooltips.vanilla_blocks_completion')
    ])
  event.add(
    [
      'minecraft:coal', 
      'minecraft:raw_copper', 
      'minecraft:raw_iron', 
      'minecraft:amethyst_shard', 
      'minecraft:raw_gold', 
      'minecraft:redstone', 
      'minecraft:lapis_lazuli', 
      'minecraft:diamond'
    ],
    [
      Text.translate('collectionTooltips.mineral_museum'), 
      Text.translate('collectionTooltips.ore_completion')
    ])
  event.add(
    [
      'regions_unexplored:argillite', 
      'regions_unexplored:chalk', 
      'regions_unexplored:mossy_stone', 
      'regions_unexplored:raw_redstone_block', 
      'regions_unexplored:hanging_prismarite', 
      'regions_unexplored:large_prismarite_cluster', 
      'regions_unexplored:blackstone_cluster', 
      'regions_unexplored:prismarite_cluster', 
      'regions_unexplored:pointed_redstone', 
      'regions_unexplored:redstone_bud', 
      'regions_unexplored:redstone_bulb'
    ],
    [
      Text.translate('collectionTooltips.mineral_museum'), 
      Text.translate('collectionTooltips.regions_unexplored_completion')
    ])

})