ItemEvents.modifyTooltips(event => {
  event.add(
    [
      'aquaculture:atlantic_cod', 
      'aquaculture:pacific_halibut', 
      'aquaculture:atlantic_halibut', 
      'aquaculture:pink_salmon', 
      'aquaculture:rainbow_trout', 
      'aquaculture:bayad', 
      'aquaculture:gar', 
      'aquaculture:muskellunge', 
      'aquaculture:tambaqui', 
      'aquaculture:red_grouper'
    ],
    [
      Text.translate('fishCraftingTableSell.you_can_sell_2_of_these_fishes'), 
      Text.translate('fishCraftingTableSell.for_5_tickets')
    ])
  event.add(
    [
      'aquaculture:blackfish', 
      'aquaculture:minnow'
    ],
    [
      Text.translate('fishCraftingTableSell.you_can_sell_2_of_these_fishes'), 
      Text.translate('fishCraftingTableSell.for_3_tickets')
    ])
  event.add(
    [
      'aquaculture:atlantic_herring', 
      'aquaculture:synodontis', 
      'aquaculture:bluegill', 
      'aquaculture:perch', 
      'aquaculture:piranha', 
      'minecraft:tropical_fish', 
      'minecraft:pufferfish'
    ],
    [
      Text.translate('fishCraftingTableSell.you_can_sell_2_of_these_fishes'), 
      Text.translate('fishCraftingTableSell.for_2_tickets')
    ])
  event.add(
    [
      'aquaculture:pollock', 
      'aquaculture:boulti', 
      'aquaculture:smallmouth_bass', 
      'aquaculture:brown_trout', 
      'aquaculture:carp', 
      'aquaculture:jellyfish', 
      'aquaculture:leech'
    ],
    [
      Text.translate('fishCraftingTableSell.you_can_sell_2_of_these_fishes'), 
      Text.translate('fishCraftingTableSell.for_4_tickets')
    ])
  event.add(
    [
      'aquaculture:capitaine', 
      'aquaculture:catfish', 
      'aquaculture:arapaima', 
      'aquaculture:arrau_turtle', 
      'aquaculture:tuna', 
      'aquaculture:box_turtle', 
      'aquaculture:starshell_turtle'
    ],
    [
      Text.translate('fishCraftingTableSell.you_can_sell_2_of_these_fishes'), 
      Text.translate('fishCraftingTableSell.for_6_tickets')
    ])
  event.add(
    [
      'aquaculture:brown_shrooma', 
      'aquaculture:red_shrooma', 
      'minecraft:cod', 
      'minecraft:salmon'
    ],
    [
      Text.translate('fishCraftingTableSell.you_can_sell_2_of_these_fishes'), 
      Text.translate('fishCraftingTableSell.for_1_tickets')
    ])

})