ItemEvents.modifyTooltips(event => {
  event.add(
    [
      'minecraft:villager_spawn_egg'
    ],
    [
      Text.translate('marketTooltips.obtainable_for_16_tickets_in_the_market')
    ])
  event.add(
    [
      'minecraft:wandering_trader_spawn_egg'
    ],
    [
      Text.translate('marketTooltips.obtainable_for_32_tickets_in_the_market')
    ])
  event.add(
    [
      'minecraft:bundle', 
      'minecraft:chorus_fruit'
    ],
    [
      Text.translate('marketTooltips.obtainable_for_8_tickets_in_the_market')
    ])
  event.add(
    [
      'minecraft:white_bed', 
      'minecraft:black_dye', 
      'minecraft:blue_dye', 
      'minecraft:brown_dye', 
      'minecraft:cyan_dye', 
      'minecraft:gray_dye', 
      'minecraft:green_dye', 
      'minecraft:light_blue_dye', 
      'minecraft:light_gray_dye', 
      'minecraft:lime_dye', 
      'minecraft:magenta_dye', 
      'minecraft:orange_dye', 
      'minecraft:pink_dye', 
      'minecraft:purple_dye', 
      'minecraft:red_dye', 
      'minecraft:white_dye', 
      'minecraft:yellow_dye'
    ],
    [
      Text.translate('marketTooltips.obtainable_for_4_tickets_in_the_market')
    ])
  event.add(
    [
      'minecraft:cod', 
      'minecraft:salmon', 
      'minecraft:tropical_fish', 
      'minecraft:pufferfish', 
      'aquaculture:smallmouth_bass', 
      'aquaculture:bluegill', 
      'aquaculture:brown_trout', 
      'aquaculture:carp', 
      'aquaculture:catfish', 
      'aquaculture:gar', 
      'aquaculture:minnow', 
      'aquaculture:muskellunge', 
      'aquaculture:perch', 
      'aquaculture:bayad', 
      'aquaculture:boulti', 
      'aquaculture:capitaine', 
      'aquaculture:synodontis', 
      'aquaculture:atlantic_cod', 
      'aquaculture:blackfish', 
      'aquaculture:pacific_halibut', 
      'aquaculture:atlantic_halibut', 
      'aquaculture:atlantic_herring', 
      'aquaculture:pink_salmon', 
      'aquaculture:pollock', 
      'aquaculture:rainbow_trout', 
      'aquaculture:jellyfish', 
      'aquaculture:red_grouper', 
      'aquaculture:tuna', 
      'aquaculture:box_turtle', 
      'aquaculture:leech', 
      'aquaculture:goldfish', 
      'aquaculture:brown_shrooma', 
      'aquaculture:red_shrooma', 
      'aquaculture:arapaima', 
      'aquaculture:piranha', 
      'aquaculture:tambaqui', 
      'aquaculture:arrau_turtle', 
      'minecraft:squid_spawn_egg', 
      'minecraft:dolphin_spawn_egg', 
      'minecraft:turtle_spawn_egg', 
      'minecraft:camel_spawn_egg', 
      'minecraft:sniffer_spawn_egg', 
      'minecraft:wolf_spawn_egg', 
      'minecraft:panda_spawn_egg', 
      'minecraft:parrot_spawn_egg', 
      'minecraft:goat_spawn_egg', 
      'minecraft:bee_spawn_egg', 
      'minecraft:allay_spawn_egg', 
      'minecraft:cat_spawn_egg', 
      'minecraft:llama_spawn_egg', 
      'minecraft:armadillo_spawn_egg', 
      'minecraft:horse_spawn_egg', 
      'minecraft:donkey_spawn_egg', 
      'minecraft:pig_spawn_egg', 
      'minecraft:chicken_spawn_egg', 
      'minecraft:rabbit_spawn_egg', 
      'minecraft:sheep_spawn_egg', 
      'minecraft:cow_spawn_egg', 
      'minecraft:bat_spawn_egg', 
      'minecraft:glow_squid_spawn_egg', 
      'minecraft:axolotl_spawn_egg', 
      'minecraft:polar_bear_spawn_egg', 
      'minecraft:fox_spawn_egg', 
      'minecraft:frog_spawn_egg', 
      'minecraft:tadpole_spawn_egg', 
      'minecraft:mooshroom_spawn_egg'
    ],
    [
      Text.translate('marketTooltips.obtainable_for_64_tickets_in_the_market')
    ])

})